name: Deploy Lambda Functions using Terraform

on:
  push:
    branches-ingore:
      - development

jobs:
  push_dev:
    runs-on: ubuntu-latest
    env:
      TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
